name: Spellcheck CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          path: src/, examples/, library.json, library.properties, README.md